title: Persona Modding Docs
description: Documentation and guides for modding Persona Games
theme: just-the-docs
color_scheme: dark

url: https://animatedswine37.github.io
baseurl: /persona-modding-docs

plugins: 
  - jekyll-tabs

aux_links:
  Discord Server: https://discord.gg/naoto  
  Amicitia Wiki: https://amicitia.miraheze.org/wiki/
  GitHub Repository: https://github.com/AnimatedSwine37/persona-modding-docs

callouts:
  warning:
    title: Warning
    color: red
  info: 
    title: Info
    color: blue
  todo:
    title: To Do
    color: yellow
  tip:
    title: Tip
    color: green

games:
- short_name: Universal
  full_name: All Games

- short_name: P3P
  full_name: Persona 3 Portable
  platform: PC 
    
- short_name: P3RE
  full_name: Persona 3 Reload
  platform: PC 
    
- short_name: P4G
  full_name: Persona 4 Golden
  platform: PC 
    
- short_name: P5R
  full_name: Persona 5 Royal
  platform: PC

- short_name: P4G Vita
  full_name: Persona 4 Golden Vita
  platform: Vita

- short_name: P3F 
  full_name: Persona 3 FES
  platform: PS2
