local_backend: true

backend:
  name: github
  repo: AnimatedSwine37/persona-modding-docs 
  branch: main
  base_url: http://ec2-13-54-217-203.ap-southeast-2.compute.amazonaws.com
  squash_merges: true
  open_authoring: true
  auth_scope: public_repo

media_folder: /assets/images
publish_mode: editorial_workflow

collections:
  - name: using-mods
    label: Using Mods
    label_singular: 'Using Mods Page'
    folder: using-mods
    media_folder: /assets/images/using-mods/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Games
        name: games
        widget: select
        options: ["Universal", "P3F", "P3P", "P3R", "P4G", "P4G Vita", "P5R"]
        multiple: true
        min: 1
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
        required: false
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: getting-started
    label: Getting Started
    label_singular: 'Getting Started Page'
    folder: getting-started
    media_folder: /assets/images/getting-started/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Games
        name: games
        widget: select
        options: ["Universal", "P3F", "P3P", "P3R", "P4G", "P4G Vita", "P5R"]
        multiple: true
        min: 1
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
        required: false
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: audio
    label: Audio
    label_singular: 'Audio Page'
    folder: audio
    media_folder: /assets/images/audio/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Games
        name: games
        widget: select
        options: ["Universal", "P3F", "P3P", "P3R", "P4G", "P4G Vita", "P5R"]
        multiple: true
        min: 1
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
        required: false
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: videos
    label: Videos
    label_singular: 'Videos Page'
    folder: videos
    media_folder: /assets/images/videos/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Games
        name: games
        widget: select
        options: ["Universal", "P3F", "P3P", "P3R", "P4G", "P4G Vita", "P5R"]
        multiple: true
        min: 1
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
        required: false
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: porting
    label: Porting
    label_singular: 'Porting Page'
    folder: porting
    media_folder: /assets/images/porting/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Games
        name: games
        widget: select
        options: ["Universal", "P3F", "P3P", "P3R", "P4G", "P4G Vita", "P5R"]
        multiple: true
        min: 1
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
        required: false
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: models
    label: Models
    label_singular: 'Models Page'
    folder: models
    media_folder: /assets/images/models/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Games
        name: games
        widget: select
        options: ["Universal", "P3F", "P3P", "P3R", "P4G", "P4G Vita", "P5R"]
        multiple: true
        min: 1
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
        required: false
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: flowscript
    label: Flowscript
    label_singular: 'Flowscript Page'
    folder: flowscript
    media_folder: /assets/images/flowscript/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Games
        name: games
        widget: select
        options: ["Universal", "P3F", "P3P", "P3R", "P4G", "P4G Vita", "P5R"]
        multiple: true
        min: 1
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
        required: false
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: text
    label: Text
    label_singular: 'Text Page'
    folder: text
    media_folder: /assets/images/text/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Games
        name: games
        widget: select
        options: ["Universal", "P3F", "P3P", "P3R", "P4G", "P4G Vita", "P5R"]
        multiple: true
        min: 1
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
        required: false
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: events
    label: Events
    label_singular: 'Events Page'
    folder: events
    media_folder: /assets/images/events/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Games
        name: games
        widget: select
        options: ["Universal", "P3F", "P3P", "P3R", "P4G", "P4G Vita", "P5R"]
        multiple: true
        min: 1
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
        required: false
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: sprites
    label: Sprites
    label_singular: 'Sprites Page'
    folder: sprites
    media_folder: /assets/images/sprites/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Games
        name: games
        widget: select
        options: ["Universal", "P3F", "P3P", "P3R", "P4G", "P4G Vita", "P5R"]
        multiple: true
        min: 1
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
        required: false
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: binary
    label: Binary Files
    label_singular: 'Binary Files Page'
    folder: binary
    media_folder: /assets/images/binary/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Games
        name: games
        widget: select
        options: ["Universal", "P3F", "P3P", "P3R", "P4G", "P4G Vita", "P5R"]
        multiple: true
        min: 1
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
        required: false
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: code
    label: Code Mods
    label_singular: 'Code Mods Page'
    folder: code
    media_folder: /assets/images/code/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Games
        name: games
        widget: select
        options: ["Universal", "P3F", "P3P", "P3R", "P4G", "P4G Vita", "P5R"]
        multiple: true
        min: 1
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
        required: false
      - label: Body
        name: body
        widget: markdown
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }

  - name: contributing
    label: Contributing
    label_singular: 'Contributing Page'
    folder: contributing
    media_folder: /assets/images/contributing/{{dirname}}
    create: true
    format: jekyll
    # adding a nested object will show the collection folder structure
    nested:
      depth: 5 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - label: Title
        name: title
        widget: string
      - label: Layout
        name: layout
        widget: hidden
        default: page
      - label: Table of Contents
        name: include_toc
        widget: boolean
        default: false
      - label: Body
        name: body
        widget: markdown